'use strict';

module.exports = {
    HTTP_OKAY: '200',
    HTTP_UNAUTHORIZED: '401',
    HTTP_FILE_NOT_FOUND: '404',
    HTTP_INVALID_ENTITY: '422',
    HTTP_INTERNAL_SERVER_ERROR: '500',

    BOOKMARK_ATTR_CREATED_ON: 'createdOn',
    BOOKMARK_ATTR_UPDATED_ON: 'updatedOn',
    BOOKMARK_ATTR_THUMB_UNREACHABLE: 'thumbUnreachable',
    BOOKMARK_ATTR_THUMB_PROCESSED_ON: 'thumbProcessedOn'
};
