BEGIN TRANSACTION;
CREATE TABLE "users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`email`	TEXT NOT NULL UNIQUE,
	`screenName`	TEXT NOT NULL UNIQUE,
	`password`      TEXT,
	`dateCreated`	TEXT
);
CREATE TABLE "token_cache" (
    `id`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    `token` TEXT NOT NULL,
    `userId`    INTEGER NOT NULL UNIQUE,
    `dateCreated` TEXT,
    `dateUpdated` TEXT
);
CREATE TABLE "bookmarks" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userId`	INTEGER NOT NULL,
	`title`	TEXT NOT NULL,
	`address`	TEXT NOT NULL,
	`dateCreated`	TEXT,
	`rating`	INTEGER,
	`starred`	INTEGER
);
CREATE TABLE "groups" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userId`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`levelNum`	INTEGER NOT NULL,
	`parentGroupId`	INTEGER,
	`dateCreated`	TEXT
);
CREATE TABLE "bookmarks_groups" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`bookmarkId`	INTEGER NOT NULL,
	`groupId`	INTEGER NOT NULL,
	`dateCreated`	TEXT
);
CREATE TABLE "tags" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`userId`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`dateCreated`	TEXT
);
CREATE TABLE "bookmarks_tags" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`bookmarkId`	INTEGER NOT NULL,
	`tagId`	INTEGER NOT NULL,
	`dateCreated`	TEXT
);
COMMIT;
